development:
  adapter: postgresql
  encoding: unicode
  database: storehouse
  pool: 5
  username: storehouse
  password: password
#  adapter: mysql2
#  encoding: utf8
#  reconnect: false
#  database: storehouse_development
#  pool: 5
#  username: root
#  password:
#  socket: /tmp/mysql.sock

test: &test
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

#production:
#  adapter: mysql2
#  host: <%= ENV['APP_DB_HOST'] %>
#  port: <%= ENV['APP_DB_PORT'] || "3306" %>
#  database: <%= ENV['APP_DB_DATABASE'] %>
#  username: <%= ENV['APP_DB_USERNAME'] %>
#  password: <%= ENV['APP_DB_PASSWORD'] %>

cucumber:
  <<: *test
