require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ExportRunsController do

  # This should return the minimal set of attributes required to create a valid
  # ExportRun. As you add validations to ExportRun, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "started_at" => "" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ExportRunsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all export_runs as @export_runs" do
      export_run = ExportRun.create! valid_attributes
      get :index, {}, valid_session
      assigns(:export_runs).should eq([export_run])
    end
  end

  describe "GET show" do
    it "assigns the requested export_run as @export_run" do
      export_run = ExportRun.create! valid_attributes
      get :show, {:id => export_run.to_param}, valid_session
      assigns(:export_run).should eq(export_run)
    end
  end

  describe "GET new" do
    it "assigns a new export_run as @export_run" do
      get :new, {}, valid_session
      assigns(:export_run).should be_a_new(ExportRun)
    end
  end

  describe "GET edit" do
    it "assigns the requested export_run as @export_run" do
      export_run = ExportRun.create! valid_attributes
      get :edit, {:id => export_run.to_param}, valid_session
      assigns(:export_run).should eq(export_run)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ExportRun" do
        expect {
          post :create, {:export_run => valid_attributes}, valid_session
        }.to change(ExportRun, :count).by(1)
      end

      it "assigns a newly created export_run as @export_run" do
        post :create, {:export_run => valid_attributes}, valid_session
        assigns(:export_run).should be_a(ExportRun)
        assigns(:export_run).should be_persisted
      end

      it "redirects to the created export_run" do
        post :create, {:export_run => valid_attributes}, valid_session
        response.should redirect_to(ExportRun.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved export_run as @export_run" do
        # Trigger the behavior that occurs when invalid params are submitted
        ExportRun.any_instance.stub(:save).and_return(false)
        post :create, {:export_run => { "started_at" => "invalid value" }}, valid_session
        assigns(:export_run).should be_a_new(ExportRun)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ExportRun.any_instance.stub(:save).and_return(false)
        post :create, {:export_run => { "started_at" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested export_run" do
        export_run = ExportRun.create! valid_attributes
        # Assuming there are no other export_runs in the database, this
        # specifies that the ExportRun created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ExportRun.any_instance.should_receive(:update_attributes).with({ "started_at" => "" })
        put :update, {:id => export_run.to_param, :export_run => { "started_at" => "" }}, valid_session
      end

      it "assigns the requested export_run as @export_run" do
        export_run = ExportRun.create! valid_attributes
        put :update, {:id => export_run.to_param, :export_run => valid_attributes}, valid_session
        assigns(:export_run).should eq(export_run)
      end

      it "redirects to the export_run" do
        export_run = ExportRun.create! valid_attributes
        put :update, {:id => export_run.to_param, :export_run => valid_attributes}, valid_session
        response.should redirect_to(export_run)
      end
    end

    describe "with invalid params" do
      it "assigns the export_run as @export_run" do
        export_run = ExportRun.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ExportRun.any_instance.stub(:save).and_return(false)
        put :update, {:id => export_run.to_param, :export_run => { "started_at" => "invalid value" }}, valid_session
        assigns(:export_run).should eq(export_run)
      end

      it "re-renders the 'edit' template" do
        export_run = ExportRun.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ExportRun.any_instance.stub(:save).and_return(false)
        put :update, {:id => export_run.to_param, :export_run => { "started_at" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested export_run" do
      export_run = ExportRun.create! valid_attributes
      expect {
        delete :destroy, {:id => export_run.to_param}, valid_session
      }.to change(ExportRun, :count).by(-1)
    end

    it "redirects to the export_runs list" do
      export_run = ExportRun.create! valid_attributes
      delete :destroy, {:id => export_run.to_param}, valid_session
      response.should redirect_to(export_runs_url)
    end
  end

end
