require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ExportRecordsController do

  # This should return the minimal set of attributes required to create a valid
  # ExportRecord. As you add validations to ExportRecord, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "record_size" => "1" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ExportRecordsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all export_records as @export_records" do
      export_set = ExportRecord.create! valid_attributes
      get :index, {}, valid_session
      assigns(:export_records).should eq([export_set])
    end
  end

  describe "GET show" do
    it "assigns the requested export_set as @export_set" do
      export_set = ExportRecord.create! valid_attributes
      get :show, {:id => export_set.to_param}, valid_session
      assigns(:export_record).should eq(export_set)
    end
  end

  describe "GET new" do
    it "assigns a new export_set as @export_set" do
      get :new, {}, valid_session
      assigns(:export_record).should be_a_new(ExportRecord)
    end
  end

  describe "GET edit" do
    it "assigns the requested export_set as @export_set" do
      export_set = ExportRecord.create! valid_attributes
      get :edit, {:id => export_set.to_param}, valid_session
      assigns(:export_record).should eq(export_set)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ExportRecord" do
        expect {
          post :create, {:export_record => valid_attributes}, valid_session
        }.to change(ExportRecord, :count).by(1)
      end

      it "assigns a newly created export_set as @export_set" do
        post :create, {:export_record => valid_attributes}, valid_session
        assigns(:export_record).should be_a(ExportRecord)
        assigns(:export_record).should be_persisted
      end

      it "redirects to the created export_set" do
        post :create, {:export_record => valid_attributes}, valid_session
        response.should redirect_to(ExportRecord.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved export_set as @export_set" do
        # Trigger the behavior that occurs when invalid params are submitted
        ExportRecord.any_instance.stub(:save).and_return(false)
        post :create, {:export_record => { "record_size" => "invalid value" }}, valid_session
        assigns(:export_record).should be_a_new(ExportRecord)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ExportRecord.any_instance.stub(:save).and_return(false)
        post :create, {:export_record => { "record_size" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested export_set" do
        export_set = ExportRecord.create! valid_attributes
        # Assuming there are no other export_records in the database, this
        # specifies that the ExportRecord created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ExportRecord.any_instance.should_receive(:update_attributes).with({ "record_size" => "1" })
        put :update, {:id => export_set.to_param, :export_record => { "record_size" => "1" }}, valid_session
      end

      it "assigns the requested export_set as @export_set" do
        export_set = ExportRecord.create! valid_attributes
        put :update, {:id => export_set.to_param, :export_record => valid_attributes}, valid_session
        assigns(:export_record).should eq(export_set)
      end

      it "redirects to the export_set" do
        export_set = ExportRecord.create! valid_attributes
        put :update, {:id => export_set.to_param, :export_record => valid_attributes}, valid_session
        response.should redirect_to(export_set)
      end
    end

    describe "with invalid params" do
      it "assigns the export_set as @export_set" do
        export_set = ExportRecord.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ExportRecord.any_instance.stub(:save).and_return(false)
        put :update, {:id => export_set.to_param, :export_record => { "record_size" => "invalid value" }}, valid_session
        assigns(:export_record).should eq(export_set)
      end

      it "re-renders the 'edit' template" do
        export_set = ExportRecord.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ExportRecord.any_instance.stub(:save).and_return(false)
        put :update, {:id => export_set.to_param, :export_record => { "record_size" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested export_set" do
      export_set = ExportRecord.create! valid_attributes
      expect {
        delete :destroy, {:id => export_set.to_param}, valid_session
      }.to change(ExportRecord, :count).by(-1)
    end

    it "redirects to the export_records list" do
      export_set = ExportRecord.create! valid_attributes
      delete :destroy, {:id => export_set.to_param}, valid_session
      response.should redirect_to(export_records_url)
    end
  end

end
